### ISSUE TITLE
bug: marks doesn't show on statuscol

### ISSUE THREAD

**Issue by KevinNitroG** [Alexis12119/nvim-config#10]
As I mentioned in my recent PR #9, the marks don't show up 😅. I found that if I remove `opts.segments` of `luukvbaal/statuscol.nvim` in [lua/plugins/nvim-ufo.lua](https://github.com/Alexis12119/nvim-config/blob/ab1c723a8ed9b31457505557f5fbae2963d7dfef/lua/plugins/nvim-ufo.lua#L24), the marks can show up.

There may be a conflict between them I guess. Currently, I have checked that the marks can show up in markdown file, other script files, even the config file cannot.

Here is the image. On the left is txt file, and on the right is markdown file.
![image](https://github.com/Alexis12119/nvim-config/assets/86353526/e107ebf2-0e9a-4d51-9857-a193f8fba8b1)

**Comment by Alexis12119** [comment]
I know why because I want to separate the diagnostics and git status signs. That's why I remove this 
```lua
{ text = { "%s" }, click = "v:lua.ScLa" },
```

**Comment by Alexis12119** [comment]
I'm currently finding way to show marks also.

**Comment by Alexis12119** [comment]
For now, I'll stick with what is working for now.

**Comment by Alexis12119** [comment]
@KevinNitroG, I wanna let you know that you can now toggle the `completion` menu to show/hide. Also, looks like it's hard to implement adding of marks at the status column.

**Comment by KevinNitroG** [comment]
> @KevinNitroG, I wanna let you know that you can now toggle the `completion` menu to show/hide. Also, looks like it's hard to implement adding of marks in the status column.

That new feature you have added will be helpful in some cases I can see in my personal usage 🤗 Thank you 😎
