### ISSUE TITLE
feat request: toggle spell-checking

### ISSUE THREAD

**Issue by KevinNitroG** [Alexis12119/nvim-config#13]
Hi, could you implement a scheme to toggle spell-checking? Also, I have a question, I don't know which plugin is in charge of checking spelling. 😄

Thank you.

**Comment by Alexis12119** [comment]
Sure, Currently I don't have plugin for spell checking. Maybe it's on the neovim side.

**Comment by Alexis12119** [comment]
For, I implemented the `vimscript` version because there are some adjustments on the `lua` version.

**Comment by Alexis12119** [comment]
Can you try the latest commit to see if it's working? @KevinNitroG

**Comment by Alexis12119** [comment]
Wait, I know now the solution for the `lua` version

**Comment by Alexis12119** [comment]
Now, try the latest one @KevinNitroG .

**Comment by KevinNitroG** [comment]
> Now, try the latest one @KevinNitroG .

Yes it works perfectly 😆 thank you again ~

**Comment by Alexis12119** [comment]
@KevinNitroG, Do you think it'll be a good idea to show the notification at the `bottom down` instead of `top down`?

Like this
![240524_21h48m44s_screenshot](https://github.com/Alexis12119/nvim-config/assets/74944536/bb42bba2-3a5d-4e15-8861-18383cc0f149)

**Comment by KevinNitroG** [comment]
> @KevinNitroG, Do you think it'll be a good idea to show the notification at the `bottom right` instead of `top right`?
> 
> Like this ![240524_21h48m44s_screenshot](https://private-user-images.githubusercontent.com/74944536/333611880-bb42bba2-3a5d-4e15-8861-18383cc0f149.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NjA5OTAsIm5iZiI6MTcxNjU2MDY5MCwicGF0aCI6Ii83NDk0NDUzNi8zMzM2MTE4ODAtYmI0MmJiYTItM2E1ZC00ZTE1LTg4NjEtMTgzODNjYzBmMTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDE0MjQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmM2E1MzU2MGU1NmZjYTRjZDllZWFjMjZiMzgyNGM2NzA1YmFjMGFiZTFkNmNlMWQxNmVjZWZjNGUxMDgxMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4k8CY-agh4u7HJvspkAtZXOUp7h9vC6HqGcsLbm17C8)

Ye actually when I started switching from vscode to neovim, I tried to find the way to make the notification at the bottom right. But later on, there were too many things for me to handle so I forgot about it 🫠
So I would be happy to have that change!!
