### ISSUE TITLE
feat request: migrate to `nvimtools/none-ls.nvim`

### ISSUE THREAD

**Issue by KevinNitroG** [Alexis12119/nvim-config#16]
Hi, it has been a while since `jose-elias-alvarez/null-ls.nvim` has been archived, `nvimtools/none-ls.nvim` came after that. The `none-ls.nvim` community has grown up and may soon overtake `stevearc/conform.nvim` and `mfussenegger/nvim-lint`. Do you think it is worth to migrate?

**Comment by Alexis12119** [comment]
I don't think I'll migrate to that since I only need `formatters` and not `linters` because most `LSP` have diagnostics out of the box.

**Comment by KevinNitroG** [comment]
> I don't think I'll migrate to that since I only need `formatters` and not `linters` because most `LSP` have diagnostics out of the box. I realized it when `null-ls.nvim` was archived.

Huhm I think what you said makes sense to me. May be I will need to take more research about those plugins.
I will close this issue 😎
