### ISSUE TITLE
bug: broken config

### ISSUE THREAD

**Issue by KevinNitroG** [Alexis12119/nvim-config#17]
In the commit `dfd898ffcfdbc836bc1f87c150858f9ae8c61e23` _(feat: adjust on `0.11`)_, in [line `66` of `nvim-lspconfig.lua`](https://github.com/Alexis12119/nvim-config/blob/dfd898ffcfdbc836bc1f87c150858f9ae8c61e23/lua/plugins/lsp/configs/nvim-lspconfig.lua#L66), you haven't handle the case if it is not `0.11`, the `config.signs` hasn't been create yet so it cannot bind `config.signs.active`

```md
   Error  8:12:11 PM notify.error lazy.nvim Failed to run `config` for nvim-lspconfig

...ta/Local/nvim/lua/plugins/lsp/configs/nvim-lspconfig.lua:66: attempt to index field 'signs' (a nil value)

# stacktrace:
  - lua/plugins/lsp/configs/nvim-lspconfig.lua:66 _in_ **config**
  - NvChad\lua\nvchad\autocmds.lua:58
  - vim\_editor.lua:431
  - telescope.nvim\lua\telescope\actions\set.lua:200 _in_ **run_replace_or_original**
  - telescope.nvim\lua\telescope\actions\mt.lua:65 _in_ **run_replace_or_original**
  - telescope.nvim\lua\telescope\actions\mt.lua:65 _in_ **run_replace_or_original**
  - telescope.nvim\lua\telescope\actions\mt.lua:65 _in_ **key_func**
  - telescope.nvim\lua\telescope\mappings.lua:293
```

Edit: I changed the title because I didn't mean to offense you 😥 Sorry for my bad English

**Comment by Alexis12119** [comment]
Alright, I'm currently trying to work both `0.10` and `0.11` and looks like I need to fix something.

**Comment by Alexis12119** [comment]
> In the commit `dfd898ffcfdbc836bc1f87c150858f9ae8c61e23` _(feat: adjust on `0.11`)_, in [line `66` of `nvim-lspconfig.lua`](https://github.com/Alexis12119/nvim-config/blob/dfd898ffcfdbc836bc1f87c150858f9ae8c61e23/lua/plugins/lsp/configs/nvim-lspconfig.lua#L66), you haven't handle the case if it is not `0.11`, the `config.signs` hasn't been create yet so it cannot bind `config.signs.active`
> 
> ```
>    Error  8:12:11 PM notify.error lazy.nvim Failed to run `config` for nvim-lspconfig
> 
> ...ta/Local/nvim/lua/plugins/lsp/configs/nvim-lspconfig.lua:66: attempt to index field 'signs' (a nil value)
> 
> # stacktrace:
>   - lua/plugins/lsp/configs/nvim-lspconfig.lua:66 _in_ **config**
>   - NvChad\lua\nvchad\autocmds.lua:58
>   - vim\_editor.lua:431
>   - telescope.nvim\lua\telescope\actions\set.lua:200 _in_ **run_replace_or_original**
>   - telescope.nvim\lua\telescope\actions\mt.lua:65 _in_ **run_replace_or_original**
>   - telescope.nvim\lua\telescope\actions\mt.lua:65 _in_ **run_replace_or_original**
>   - telescope.nvim\lua\telescope\actions\mt.lua:65 _in_ **key_func**
>   - telescope.nvim\lua\telescope\mappings.lua:293
> ```
> 
> Edit: I changed the title because I didn't mean to offense you 😥 Sorry for my bad English

I have an else command that'll execute for the previous versions of neovim. I just thought I can just put it directly. Thanks for filing this issue.

**Comment by Alexis12119** [comment]
Can you test the latest version now? @KevinNitroG

**Comment by Alexis12119** [comment]
Still not working on you @KevinNitroG ?

**Comment by Alexis12119** [comment]
I'll close this issue now.

**Comment by KevinNitroG** [comment]
> Still not working on you @KevinNitroG ?

Yeye thank you it works now :). I'm doing some coding homework and I forget to check your commits. Thank you again 😁
