### ISSUE TITLE
bug: always reload `lua_ls` libraries references

### ISSUE THREAD

**Issue by KevinNitroG** [Alexis12119/nvim-config#19]
I don't know how to say it, perhaps it's called "libraries", "references"? Could you watch this video and check it does it happen to yours too?

![Video](https://github.com/Alexis12119/nvim-config/assets/86353526/582c42f7-293a-4f0d-9635-bfcedd82ffe9)

just type `vim.` and then every time I save the file? it will reload the "libraries references"? If it is a problem, I guess... maybe it comes from `folke/lazydev.nvim` and `luvit-meta/library` you have just added in [8915329466d121a4c73d6405a73d21a14f6c4434](https://github.com/Alexis12119/nvim-config/commit/8915329466d121a4c73d6405a73d21a14f6c4434)

**Comment by Alexis12119** [comment]
I think this is a of `lazydev.nvim`.  I can't uninstall `lazydev.nvim` because it provides a good documentation of the function so that I won't need to go in the neovim docs.

**Comment by Alexis12119** [comment]
https://github.com/Alexis12119/nvim-config/assets/74944536/1445dbb3-e835-41a3-90f5-3d016faf583f

**Comment by KevinNitroG** [comment]
> 2024-06-06.07-54-04.mp4

https://github.com/Alexis12119/nvim-config/assets/86353526/c7f42db4-6ba7-4a75-aea1-414a96f7bdb7

It happens on my Windows too :)

But never mind, it doesn't matter if it is your need. 😁
