### ISSUE TITLE
How to customize formatting？

### ISSUE THREAD

**Issue by Y0J1G3N** [Alexis12119/nvim-config#2]
I used your neovim configuration, but I don’t know how to use the null-ls plugin to format my c++ code. The default is to use 2 indents, and I want to change it to 4 indents. How does the :Format command work? Is the formatting of lsp called by default?

**Comment by Alexis12119** [comment]
Hi, Good morning to you.

This is my function for the formatting logic.

https://github.com/Alexis12119/nvim-config/blob/main/lua/core/utils.lua#L19-L38

What it does is check if the `null-ls` is attached and has a  formatting capability. If not, then the lsp attached that has formatting capability will be used for formatting.

This is the `Format` command.
https://github.com/Alexis12119/nvim-config/blob/main/lua/core/utils.lua#L98-L101

The format command is calling the `format_code()` function to format the file and I mapped the `:Format` command to `<space>lf`.

Also, I'm using `.clang-format` to customize how the `clang-format` will format my `cpp` file.  You can use `.clang-format` to change the indent to `4`.

Before formatting the file
![Screenshot (66)](https://github.com/Alexis12119/nvim-config/assets/74944536/73a5840d-ce23-40e1-ab10-842c066f0dbd)


After formatting file through `:Format` or `<leader>lf`
![Screenshot (67)](https://github.com/Alexis12119/nvim-config/assets/74944536/68fc4853-afc6-4573-b736-dae486e2f3ef)


Hope it helps.

**Comment by Alexis12119** [comment]
Is my explanation easy to understand? Because I feel like it's too long.

**Comment by Y0J1G3N** [comment]
I see,I also use clang-format to format my cpp file but I still don't know how to change the indent to 4.is it in null-ls?Is it configured in null-ls? What is the relevant documentation like? I have installed clang_format by mason, and the command :NullLsInfo shows that clang_format is working correctly.

**Comment by Alexis12119** [comment]
I created the `.clang-fomat` inside the directory of my `cpp` file.

![Screenshot (68)](https://github.com/Alexis12119/nvim-config/assets/74944536/9d2cbf85-ed12-4b7c-896c-5ef4b7177c51)

**Comment by Y0J1G3N** [comment]
I see,thank you,your nvim-config has been help me a lot.

**Comment by Y0J1G3N** [comment]
There is a peculiar phenomenon where, after creating the .clang-format file, I am able to use 4-space indentation correctly. However, even after deleting the null-ls.lua file, it still retains the 4-space indentation. According to my understanding, at this point, it should be using the formatting of the LSP. Is the null-ls.lua file really having an effect?

**Comment by Alexis12119** [comment]
I just noticed there's a weird behaviour on formatting the file using `<space>lf>`, but when I'm using the `:Format` command it formats the file correctly.

![Screenshot (69)](https://github.com/Alexis12119/nvim-config/assets/74944536/b2b406cd-e8d3-42d5-9a7e-9fed75a5e0fa)


Sorry, I just read your comment just now.

**Comment by Alexis12119** [comment]
I just noticed that `clangd` also uses `.clang-format`. It looks like I don't really need `clang-format`.

**Comment by Alexis12119** [comment]
Look here:

Not same directory of `.clang-format` and cpp file.
![Screenshot (70)](https://github.com/Alexis12119/nvim-config/assets/74944536/81d24be5-4749-4bdf-ab75-d015645148a2)

Same directory of `.clang-format` and cpp file.
![Screenshot (71)](https://github.com/Alexis12119/nvim-config/assets/74944536/5aaee2ea-3ce2-4085-825d-541cb1e361f5)

**Comment by Y0J1G3N** [comment]
My requirement has already been resolved. I prefer not to add a `.clang-format` file to every cpp project, so I followed the link below to resolve it.
https://github.com/jose-elias-alvarez/null-ls.nvim/discussions/953

**Comment by Alexis12119** [comment]
Thanks, I'll add it to my `clang-format` configuration
