### ISSUE TITLE
where's your statusline?

### ISSUE THREAD

**Issue by daUnknownCoder** [Alexis12119/nvim-config#21]
i came here from 
![image](https://github.com/Alexis12119/nvim-config/assets/84800625/45caa742-2a2e-413e-b857-61ef4d1399ef)

from this post: https://new.reddit.com/r/neovim/comments/xtynan/show_me_your_statusline_big_plus_if_you_wrote_it/

**Comment by Alexis12119** [comment]
I used `NvChad` now so I'm using their statusline now with some modifications.

**Comment by Alexis12119** [comment]
But, here's my function that I created for my statusline.
https://github.com/Alexis12119/nvim-config/blob/main/lua/chadrc.lua#L66-L199

**Comment by daUnknownCoder** [comment]
so can i get the previous statusline commit or blob?

**Comment by Alexis12119** [comment]
Maybe this
https://github.com/Alexis12119/nvim-config/blob/e394c853654164f8ebe7d9d1009449a35571d1dd/lua/plugins/lualine/components.lua

**Comment by daUnknownCoder** [comment]
> Maybe this https://github.com/Alexis12119/nvim-config/blob/e394c853654164f8ebe7d9d1009449a35571d1dd/lua/plugins/lualine/components.lua

~arigato~ Thank You!
