### ISSUE TITLE
feat request: pre-config `actionlint` for `nvim-lint`

### ISSUE THREAD

**Issue by KevinNitroG** [Alexis12119/nvim-config#22]
Hi (:

I think you want your nvim config to serve all kinds of coder/dev and want to make it easy to config. So I think it would be nice to pre-config `actionlint` in the `nvim-lint` plugin. It wouldn't matter if the `actionlint` isn't installed while `nvim-lint` is enabled _(no error show)_. And if anyone wants to set up `actionlint`, they just need to install the executable _(via Mason...)_.

Here is my current config:
- [lua/plugins/lsp/configs/nvim-lint.lua](https://github.com/KevinNitroG/Alexis12119-nvim/blob/13fffe6dcde860b9f46e458404fb1f5216df12ed/lua/plugins/lsp/configs/nvim-lint.lua#L17)
- [lua/core/filetypes.lua](https://github.com/KevinNitroG/Alexis12119-nvim/blob/13fffe6dcde860b9f46e458404fb1f5216df12ed/lua/core/filetypes.lua#L7-L10)

> [!NOTE]
>
> ref: https://github.com/mfussenegger/nvim-lint/issues/591#issuecomment-2142162704

---

If you want, I can create a PR for you.

**Comment by Alexis12119** [comment]
Many thanks
