### ISSUE TITLE
bug(`persisted.nvim`): typo issue in mapping

### ISSUE THREAD

**Issue by KevinNitroG** [Alexis12119/nvim-config#26]
https://github.com/Alexis12119/nvim-config/blob/0f52a80b5dea83950e62e1971b71ea2263b28553/lua/plugins/persisted.lua#L7-L8

Hi there is a typo issue :)) `SessionLoadLast`

**Comment by Alexis12119** [comment]
Fixed. Thanks for reporting. I didn't noticed it because i disabled that plugin.
