### ISSUE TITLE
convention: `cinnamon.lua` format

### ISSUE THREAD

**Issue by KevinNitroG** [Alexis12119/nvim-config#29]
Hi ^^. Seem that you didn't format the code following `.stylua.toml` right? Because the tab is space 2 mixed with space 4, also the comment sections are different when using stylua format, which makes it hard to sync with your upstream to my (our) downstream.

https://github.com/Alexis12119/nvim-config/blob/1365aaf30c2b8cb353cbece248b11c233737a42c/lua/plugins/cinnamon.lua

**Comment by Alexis12119** [comment]
Can you create a pull request? I'm not in home right now. Thanks

**Comment by KevinNitroG** [comment]
> Can you create a pull request? I'm not in my home right now. Thanks

Yes but I'm gonna take a nap right now 😁 I will create PR 2 hours latter 🐧

**Comment by KevinNitroG** [comment]
Hi I have created a PR for this.😁
