### ISSUE TITLE
`nvim-treesitter` class selection mode logic

### ISSUE THREAD

**Issue by KevinNitroG** [Alexis12119/nvim-config#31]
Currently, the config for selecting around the class is visual block mode, which I think doesn't make sense and is helpful. I think it should be visual line mode for example `vac` to Visual Around the Class, `dac` to Delete Around the Class...

---

Current config: 

https://github.com/Alexis12119/nvim-config/blob/9b819017977e917b40aa770a33f737c29166364f/lua/plugins/nvim-treesitter.lua#L162-L166

My suggestion:

```diff
        selection_modes = {
          ["@parameter.outer"] = "v", -- charwise
          ["@function.outer"] = "V", -- linewise
-          ["@class.outer"] = "<c-v>", -- clockwise
+          ["@class.outer"] = "V", -- linewise
        },
```

**Comment by Alexis12119** [comment]
Alright, create a pr for it

**Comment by Alexis12119** [comment]
Alright, I'm in my home now so I can make the changes now.
