### ISSUE TITLE
conflict keymap in `supermaven-nvim`

### ISSUE THREAD

**Issue by KevinNitroG** [Alexis12119/nvim-config#33]
The `<C-j>` for `accept_word` of `supermaven-nvim` is already mapped to `General | Go to upper window`. 😗

https://github.com/Alexis12119/nvim-config/blob/bf201fe252d8b23a09b7d0fa368737107db36e38/lua/plugins/nvim-cmp.lua#L57-L69

https://github.com/Alexis12119/nvim-config/blob/bf201fe252d8b23a09b7d0fa368737107db36e38/lua/mappings.lua#L107-L108

**Comment by Alexis12119** [comment]
Then, I'll probably go back to codeium because it has better integration for `nvim-cmp`. I'll migrate once it's matured enough.
