### ISSUE TITLE
cannot run `html` file

### ISSUE THREAD

**Issue by KevinNitroG** [Alexis12119/nvim-config#35]
with the current config, in my case, running (opening) HTML on the browser doesn't work.

https://github.com/Alexis12119/nvim-config/blob/77bca73e64dac01a74830299a93558b8b27915ac/lua/core/utils.lua#L72C1-L75C1

I don't know if it is your purpose or not. But if so, I suggest config like this:

```lua
    html = {
      default = "firefox %", -- NOTE: change the browser based on your choice
    },
```

**Comment by Alexis12119** [comment]
Alright, thanks  for that.
