### ISSUE TITLE
question about "signature help" and "documentation hover"

### ISSUE THREAD

**Issue by KevinNitroG** [Alexis12119/nvim-config#36]
You don't use Noice's `lsp.hover` and `lsp.signature` in your config, right? I don't know the reason why is that.

Recently I have found a way to use Noice's config instead of your current config because the markdown type in hover and signature has the `conceallevel = 0` which makes me quite annoyed. With Noice's config, it renders better :))

We have to set up nvchad's lsp signature to false following this comment first (https://github.com/NvChad/NvChad/issues/1656#issuecomment-2082408141).

I can make a PR for this.

**Comment by Alexis12119** [comment]
Because it conflicts with `nvim-lspconfig`, but based on what you said then I'll just use what `noice.nvim` have. Thanks for that.

**Comment by KevinNitroG** [comment]
> Because it conflicts with `nvim-lspconfig`, but based on what you said then I'll just use what `noice.nvim` have. Thanks for that.

Huhm currently I don't see any error, and there's no modification in `lua/plugins/lsp/config/nvim-lspconfig.lua`. And I didn't get what you said :)) will you try the Noice's hover and signature help? I will make a PR for you 😎

**Comment by Alexis12119** [comment]
> > Because it conflicts with `nvim-lspconfig`, but based on what you said then I'll just use what `noice.nvim` have. Thanks for that.
> 
> Huhm currently I don't see any error, and there's no modification in `lua/plugins/lsp/config/nvim-lspconfig.lua`. And I didn't get what you said :)) will you try the Noice's hover and signature help? I will make a PR for you 😎

I commented the config related to the borders that's why hehe

**Comment by Alexis12119** [comment]
> > Because it conflicts with `nvim-lspconfig`, but based on what you said then I'll just use what `noice.nvim` have. Thanks for that.
> 
> Huhm currently I don't see any error, and there's no modification in `lua/plugins/lsp/config/nvim-lspconfig.lua`. And I didn't get what you said :)) will you try the Noice's hover and signature help? I will make a PR for you 😎

I just upload a commit for it.

**Comment by KevinNitroG** [comment]
> > > Because it conflicts with `nvim-lspconfig`, but based on what you said then I'll just use what `noice.nvim` have. Thanks for that.
> > 
> > 
> > Huhm currently I don't see any error, and there's no modification in `lua/plugins/lsp/config/nvim-lspconfig.lua`. And I didn't get what you said :)) will you try the Noice's hover and signature help? I will make a PR for you 😎
> 
> I just uploaded a commit for it.

Alright ☑️

**Comment by Alexis12119** [comment]
I removed the `nvim-lspconfig` conflict, but still got this issue.
```lua
`vim.lsp.handlers["textDocument/signatureHelp"]` has been overwritten by another plugin?

Either disable the other plugin or set `config.lsp.signature.enabled = false` in your **Noice** config.
  - plugin: nvim
  - file: /usr/local/share/nvim/runtime/lua/vim/lsp.lua
  - line: 1169
```

**Comment by Alexis12119** [comment]
wait, I think I'll disable the lsp signature of `NvChad`.
