### ISSUE TITLE
option to enable border

### ISSUE THREAD

**Issue by KevinNitroG** [Alexis12119/nvim-config#37]
I have the config to enable border in lsp windows (lpsinfo), lazy (`<leader>ph`), mason (`<leader>lm`), lspsaga? (I have forgot what of it use border ._.), which-key (whenever trigger whichkey), nvim-cmp.

I think it's great to have this for guys who like transparent like me :). 

![image](https://github.com/user-attachments/assets/375748a8-4329-4457-93ca-726b58cfb07b)
![image](https://github.com/user-attachments/assets/e7622071-9bb5-4b69-b297-913640c13fbd)
![image](https://github.com/user-attachments/assets/2eb683fb-53a0-40e8-8aa1-89f52859db48)
![image](https://github.com/user-attachments/assets/5874719b-4c02-48de-bfd1-5b719000cf66)

---

### OOPS

Because lazy need to set up before the `lua/options.lua` load, so I can only put the option `vim.g.border_enabled = true` in `init.lua`

![image](https://github.com/user-attachments/assets/f6aea573-2d86-455d-b566-9420cdc855ca)

And I can make a PR for this.

**Comment by Alexis12119** [comment]
Yeah, it's fine and create a PR for it. Thanks

**Comment by Alexis12119** [comment]
Oh, wait if we put that global var in the `init.lua` the user won't see it easily

**Comment by Alexis12119** [comment]
I'll watch anime so I won't be able to respond :laughing:.

**Comment by KevinNitroG** [comment]
> Oh, wait if we put that global var in the `init.lua` the user won't see it easily

It's a trade-off :)) Anyway happy anime watching time 👀

**Comment by KevinNitroG** [comment]
I have created a PR for this.

**Comment by Alexis12119** [comment]
> I have created a PR for this.

Alright, I'll merge it then watch
