### ISSUE TITLE
Question about keymap in plugins

### ISSUE THREAD

**Issue by KevinNitroG** [Alexis12119/nvim-config#39]
Hi 👀 In your config, you are setting keymaps using vim's API, but I wonder what is the reason why you chose that instead of LazyNvim's key lazy load?

---

With LazyNvim, we can set the `iamcco/markdown-preview.nvim` to only show the keymap on the markdown filetype. We can also set `linux-cultist/venv-selector.nvim` to load on python filetype...

Also with other plugins, we can easily trigger it to load with keys when it doesn't provide the `<cmd>...<cr>` way, which currently we have to load it in the specific event before using the keymap 😔. And that's not optimised for lazy loading.

**Comment by Alexis12119** [comment]
To have an easy way especially when migrating as you can see i can just copy and paste in my current way. I noticed it when i migrated to 2.5 of NvChad and also it won't add abstraction to the user when creating keymaps. I hope it makes sense to you.

**Comment by KevinNitroG** [comment]
> To have an easy way especially when migrating as you can see i can just copy and paste in my current way. I noticed it when i migrated to 2.5 of NvChad and also it won't add abstraction to the user when creating keymaps. I hope it makes sense to you.

Alright, I got it 🥰
