### ISSUE TITLE
`nvim-tmux-navigation` config can be improved

### ISSUE THREAD

**Issue by KevinNitroG** [Alexis12119/nvim-config#40]
Hello :) I think `alexghergh/nvim-tmux-navigation` config can be improved for better loading. But this is just my opinion. I wouldn't be sad if you discarded this idea 👀.

Currently, if we are not on Windows, `nvim-tmux-navigation` will be enabled and loaded on `VeryLazy`. But if someone doesn't use tmux, it is always enabled and loaded despite that.

I have 2 options.

---

### 1. Keep the original code convention

```lua
-- NOTE: Tmux navigation
local plugin = {
  "alexghergh/nvim-tmux-navigation",
  event = "VeryLazy",
  cond = vim.fn.executable "tmux" == 1,
  enabled = vim.env.TMUX ~= nil,
  opts = {
    keybindings = {
      left = "<C-h>",
      down = "<C-j>",
      up = "<C-k>",
      right = "<C-l>",
      last_active = "<C-\\>",
      next = "<C-Space>",
    },
  },
}
```

This way, the plugin will only be downloaded if there's `tmux` command.

> [!NOTE]
>
>The downside of this approach is that if nvim start with not in tmux, the plugin is marked as disabled, and can be cleaned if we press `X` in Lazy (clean). And then if nvim start in tmux, it will download the plugin again.

### 2. Fix the above downside but the code convention changed

Like my wakatime config before

```lua
-- NOTE: Tmux navigation
local plugin = {
  "alexghergh/nvim-tmux-navigation",
  cond = vim.fn.executable "tmux" == 1,
  opts = {
    keybindings = {
      left = "<C-h>",
      down = "<C-j>",
      up = "<C-k>",
      right = "<C-l>",
      last_active = "<C-\\>",
      next = "<C-Space>",
    },
  },
}

if vim.env.TMUX ~= nil then
  plugin.event = "VeryLazy"
end

return plugin
```

**Comment by KevinNitroG** [comment]
Edit
I have found out that `event` can be `nil` :)). The config now should be cleaner and more readable

```lua
-- NOTE: Tmux navigation
return {
  "alexghergh/nvim-tmux-navigation",
  cond = vim.fn.executable "tmux" == 1,
  event = vim.env.TMUX ~= nil and "VeryLazy" or nil,
  opts = {
    keybindings = {
      left = "<C-h>",
      down = "<C-j>",
      up = "<C-k>",
      right = "<C-l>",
      last_active = "<C-\\>",
      next = "<C-Space>",
    },
  },
}
```

**Comment by Alexis12119** [comment]
Alright, create a pr for it.

**Comment by KevinNitroG** [comment]
I have created PR for it
