### ISSUE TITLE
Question about preload library of `lua_ls`

### ISSUE THREAD

**Issue by KevinNitroG** [Alexis12119/nvim-config#42]
You have added `---@type NvPluginSpec` on every before return which can show Lazy's specs suggestion right? But it doesn't show all Lazy's specs.

I have figured out that adding `settings.Lua.workspace.libary = {..., vim.fn.stdpath "data" .. "/lazy/lazy.nvim/lua/lazy/types.lua"}` in `lua/plugins/lsp/settings/lua_ls.lua` can show all Lazy's specs. But I don't know if it is the right way or good to do that.

**Comment by Alexis12119** [comment]
The completions are from [here](https://github.com/NvChad/ui/blob/v2.5/nvchad_types/plugins.lua). It also won't show the `opts` that's already presented. Also, maybe the the types here's aren't updated that's why it doesn't show all Lazy specs.

**Comment by Alexis12119** [comment]
Maybe I can try this type `---@type PluginOpts`
