### ISSUE TITLE
`friendly-snippets` is installed but not in used

### ISSUE THREAD

**Issue by KevinNitroG** [Alexis12119/nvim-config#43]
I just want to tell you that `rafamadriz/friendly-snippets` is installed but not in used.

I suggest add this to `lua/plugins/nvim-cmp.lua`

```lua
	...
	config = function(_, opts)
		...
		require("luasnip.loaders.from_vscode").lazy_load()
	end,
	...
```

---

Also extend `javascript` with react by adding

```lua
	...
	config = function(_, opts)
		...
		require("luasnip").filetype_extend("javascript", { "javascriptreact" })
    	require("luasnip").filetype_extend("typescript", { "typescriptreact" })
	end,
	...
```

**Comment by Alexis12119** [comment]
Looks like they remove the code that enables `rafamadriz/friendly-snippets`.

**Comment by Alexis12119** [comment]
Wait, but I can still the snippets from `friendly-snippets`.

**Comment by Alexis12119** [comment]
The `friendly-snippets` is being used though

**Comment by Alexis12119** [comment]
But, I'll keep the code that extend snippets. Thanks

**Comment by KevinNitroG** [comment]
> The `friendly-snippets` is still being use though

Oh maybe it was my mistake 💩
