### ISSUE TITLE
issue: toggle notification in mapping

### ISSUE THREAD

**Issue by KevinNitroG** [Alexis12119/nvim-config#46]
the toggle transparent & theme in `mappings.lua` code logic isn't good. Those `vim.g.switch_theme`, `vim.g.transparency_enabled` are `nil` by default.

We use dark mode. But if someone uses light mode, when he switches to dark mode, the notification shows that he has switched to light mode.

So I suggest binding the global variables in `chadrc.lua` to get those variables.

```lua
vim.g.darkmode_enabled = M.base46.theme_toggle[1] == M.base46.theme
vim.g.transparency_enabled = M.base46.transparency
```

I don't know if we need to handle it if there's no `M.base46.theme_toggle`.

**Comment by Alexis12119** [comment]
If you can create a PR for it. Please, create one I'm just busy right now.

**Comment by Alexis12119** [comment]
> I don't know if we need to handle it if there's no `M.base46.theme_toggle`.

I think it always exist

**Comment by Alexis12119** [comment]
Wait, the one for transparency is fine

**Comment by KevinNitroG** [comment]
> > I don't know if we need to handle it if there's no `M.base46.theme_toggle`.
> 
> I think it always exist

There's a notification to add it when there's no `M.base46.theme_toggle`

**Comment by Alexis12119** [comment]
I think it's fine to leave both of them as it is.

**Comment by Alexis12119** [comment]
> > > I don't know if we need to handle it if there's no `M.base46.theme_toggle`.
> > 
> > 
> > I think it always exist
> 
> There's a notification to add it when there's no `M.base46.theme_toggle`

oh, maybe because of the recent changes that siduck made.

**Comment by Alexis12119** [comment]
I noticed that `theme_toggle` isn't updating.

**Comment by Alexis12119** [comment]
siduck is now gonna fix that bug.
