### ISSUE TITLE
Question about `nvim-cmp` config

### ISSUE THREAD

**Issue by KevinNitroG** [Alexis12119/nvim-config#54]
Your `nvim-cmp` have the following setup

https://github.com/Alexis12119/nvim-config/blob/697d5b2c15f20700b06161b9ae1010a20d120461/lua/plugins/nvim-cmp.lua#L31-L42

https://github.com/Alexis12119/nvim-config/blob/697d5b2c15f20700b06161b9ae1010a20d120461/lua/plugins/nvim-cmp.lua#L73-L77

---

I don't know what exactly the `nvim-cmp.opt.formatting` do but it makes https://github.com/kristijanhusak/vim-dadbod-completion not showing its icon.

But I wonder can we just remove those lines, and add to opts to lspkind? Does it load NvChad's lspkind icons? Because this way, https://github.com/kristijanhusak/vim-dadbod-completion can show its icon on cmp.

```diff
  dependencies = {
    -- Icons
    {
      "onsails/lspkind.nvim",
+     opts = {
+       symbol_map = require "nvchad.icons.lspkind"
+     },
    },
  }
```

**Comment by KevinNitroG** [comment]
Confirm NvChad's icons are loaded

**Comment by KevinNitroG** [comment]
I suggest this for easier to add user's icons

```lua
    {
      "onsails/lspkind.nvim",
      opts = {
        symbol_map = vim.tbl_extend("force", require "nvchad.icons.lspkind", {
          -- Your custom icons go here
        }),
      },
    },
```

**Comment by KevinNitroG** [comment]
I think NvChad's icons are loaded itself (in chadrc.lua) and there's no affect by declare opts in lspkind

**Comment by Alexis12119** [comment]
Alright, I'll put it in the `lspkind.nvim` for now, but there's also one other way which is extend the  icons of `NvChad` lspkind.

**Comment by Alexis12119** [comment]
```lua
    -- Icons
    {
      "onsails/lspkind.nvim",
      config = function()
        local icons = require "nvchad.icons.lspkind"

        require("cmp").formatting = {
          format = function(entry, vim_item)
            local kind = require("lspkind").cmp_format { mode = "text", maxwidth = 50 }(entry, vim_item)
            local strings = vim.split(kind.kind, " ", { trimempty = true })
            kind.kind = string.format(" %s  %s", icons[vim_item.kind], strings[1])
            kind.menu = " " .. (strings[2] or "") .. ""

            return kind
          end,
        }
      end,
    },
```

**Comment by Alexis12119** [comment]
Is this fine?

**Comment by Alexis12119** [comment]
Wait, I'll send the code for the another way.

**Comment by Alexis12119** [comment]
Through this I can edit how the completion looks line and the logic in this code is add some space between the icon and text.
```lua
 opts.formatting = { 
   format = function(entry, vim_item) 
     local kind = require("lspkind").cmp_format { mode = "text", maxwidth = 50 }(entry, vim_item) 
     local strings = vim.split(kind.kind, " ", { trimempty = true }) 
     kind.kind = string.format(" %s  %s", icons[vim_item.kind], strings[1]) 
     kind.menu = " " .. (strings[2] or "") .. "" 
  
     return kind 
   end, 
```

**Comment by Alexis12119** [comment]
Looks like `vim-dadbod-completion` is being read as sources to be specific as `Text`. If you can see the active `source` which is `vim-dadbod-completion`.

**Comment by Alexis12119** [comment]
If you check `:CmpStatus`, you can see that `vim-dadbod-completion` is the only active and in completion shows as `Text`.

**Comment by Alexis12119** [comment]
I wish it has a custom name for the icon so that we can add/override one.

**Comment by Alexis12119** [comment]
But, we can also adjust the icon of it in the `sources`

**Comment by KevinNitroG** [comment]
> But, we can also adjust the icon of it in the `sources`

Sorry I was bruh. I meant the `[DB]` not the "icon" :)) I think this is enough although it's a text suggestion.

![image](https://github.com/user-attachments/assets/a828b49c-1eaf-48ec-8042-1f2fd7ede6b2)

**Comment by Alexis12119** [comment]
Alright, let me investigate.

**Comment by Alexis12119** [comment]
@KevinNitroG, how about this?
![Uploading 240810_21h40m36s_screenshot.png…]()

**Comment by KevinNitroG** [comment]
`` is this better than that ? :))

**Comment by Alexis12119** [comment]
I need to do something now, but this is just what I did.
```lua
    opts.formatting = {
      format = function(entry, vim_item)
        local kind = require("lspkind").cmp_format { mode = "text", maxwidth = 50 }(entry, vim_item)
        local strings = vim.split(kind.kind, " ", { trimempty = true })
        kind.kind = string.format(" %s  %s", icons[vim_item.kind], strings[1])
        kind.menu = " " .. (strings[2] or "") .. ""
        kind.menu = ({
          ["vim-dadbod-completion"] = "",
        })[entry.source.name]

        return kind
      end,
    }

    vim.api.nvim_create_autocmd("FileType", {
      pattern = { "sql", "mysql", "plsql" },
      callback = function()
        require("cmp").setup.buffer { sources = { { name = "vim-dadbod-completion" } } }
      end,
    })
```

**Comment by Alexis12119** [comment]
> 

Oh, you're right. I just used the one `supermaven` suggested to me.

**Comment by KevinNitroG** [comment]
Thank you very much ((:

Btw why do you declare yourself the `opts.formatting`? Because I see no different without it so I just wonder 😶

**Comment by KevinNitroG** [comment]
But I'm confused a bit why did you declare twice `kind.menu`?

```lua
        kind.menu = " " .. (strings[2] or "") .. ""
        kind.menu = ({
          ["vim-dadbod-completion"] = "",
        })[entry.source.name]
```

**Comment by Alexis12119** [comment]
add more space between the text and icon

**Comment by KevinNitroG** [comment]
> add more space between the text and icon

and is the `""` at the end odd? :))

```lua
        kind.menu = " " .. (strings[2] or "") .. "" -- <-- this!
```

**Comment by Alexis12119** [comment]
> But I'm confused a bit why did you declare twice `kind.menu`?
> 
> ```lua
>         kind.menu = " " .. (strings[2] or "") .. ""
>         kind.menu = ({
>           ["vim-dadbod-completion"] = "",
>         })[entry.source.name]
> ```

Just the modify the one for `vim-dadbod-completion`

**Comment by Alexis12119** [comment]
I'm just cooking rice so that once I wake up in the morning. I don't need to cook it and saves my time since I need to go out early :). That's why I made that  not so well though solution :).

**Comment by Alexis12119** [comment]
> > add more space between the text and icon
> 
> and is the `""` at the end odd? :))
> 
> ```lua
>         kind.menu = " " .. (strings[2] or "") .. "" -- <-- this!
> ```

yeah

**Comment by KevinNitroG** [comment]
> I'm just cooking rice so that once I wake up in the morning. I don't need to cook it and saves my time since I need to go out early :). That's why I made that not so well though solution :).

hehe lol :))

**Comment by KevinNitroG** [comment]
Can we remove the `kind.menu`? and Let the lspkind handle it

```lua
    local menu = {
      ["vim-dadbod-completion"] = "", -- Not working
    }
    opts.formatting = {
      format = function(entry, vim_item)
        local kind = require("lspkind").cmp_format { mode = "text", menu = menu, maxwidth = 50 }(entry, vim_item)
        local strings = vim.split(kind.kind, " ", { trimempty = true })
        kind.kind = string.format(" %s  %s", icons[vim_item.kind], strings[1])
        kind.menu = " " .. (kind.menu or "")
        return kind
      end,
    }
```

**Comment by Alexis12119** [comment]
Alright
