### ISSUE TITLE
Is it normal when there's 2 tsserver running while coding JS?

### ISSUE THREAD

**Issue by KevinNitroG** [Alexis12119/nvim-config#57]
When I code JS, just a single file or a project, there are 2 tsserver running. I just wonder is it normal?

Because they both consume the same resource, but different commands. Maybe it's relate to https://github.com/pmizio/typescript-tools.nvim?

```
 ps aux | rg tss
kevinni+   65529 15.8  0.6 1087756 167376 ?      Ssl  18:58   0:02 node /home/kevinnitro/.local/share/nvim/mason/packages/typescript-language-server/node_modules/typescript/lib/tsserver.js --stdio --locale en --useInferredProjectPerProjectRoot --validateDefaultNpmLocation --noGetErrOnBackgroundUpdate --cancellationPipeName /tmp/tsserver_nvim_jGg8qf/seq_*
kevinni+   65531 14.1  0.8 1118476 209928 ?      Ssl  18:58   0:01 node /home/kevinnitro/.local/share/nvim/mason/packages/typescript-language-server/node_modules/typescript/lib/tsserver.js --stdio --locale en --useInferredProjectPerProjectRoot --validateDefaultNpmLocation --noGetErrOnBackgroundUpdate --cancellationPipeName /tmp/tsserver_nvim_Od3zd9/seq_*
kevinni+   66085  0.0  0.0   8884  6108 pts/7    S+   18:59   0:00 rg tss
```

![image](https://github.com/user-attachments/assets/8113bf6a-5f57-40f6-af8e-08c77ec9dadb)

does it happen on yours? 😦

**Comment by Alexis12119** [comment]
Nope

**Comment by Alexis12119** [comment]
oh, maybe due to some options of `volar`

**Comment by Alexis12119** [comment]
Wait, Lemme investigate but I think it's related to my `opts` in `volar`

**Comment by Alexis12119** [comment]
I set this `opt` to true because of [this](https://github.com/LazyVim/LazyVim/commit/4b0f720457fbbf624406a540b42e9ad7f2e50a77)

**Comment by Alexis12119** [comment]
Is that from `node_modules`?

**Comment by Alexis12119** [comment]
Maybe, `typescript-tools.nvim` is really the culprit here

**Comment by Alexis12119** [comment]
I tried `vtsls` and works fine

**Comment by Alexis12119** [comment]
Even `vtsls` is running two process.

**Comment by Alexis12119** [comment]
But, maybe due to `ts` plugins

**Comment by Alexis12119** [comment]
I have 4 tsserver process running :laughing:

**Comment by Alexis12119** [comment]
I just commented this and now I have one process.

https://github.com/Alexis12119/nvim-config/blob/main/lua/plugins/lsp/settings/vtsls.lua#L13-L23

**Comment by Alexis12119** [comment]
But, it's needed for making `tsserver` on the `vue` files

**Comment by Alexis12119** [comment]
Wait, I thought I fixed  it now, but it's not.

**Comment by KevinNitroG** [comment]
> Wait, I thought I fixed it now, but it's not.

🐧🐧

**Comment by Alexis12119** [comment]
maybe that's a default behaviour

**Comment by KevinNitroG** [comment]
> maybe that's a default behaviour

I don't believe that ((:

**Comment by KevinNitroG** [comment]
But doesn't https://github.com/pmizio/typescript-tools.nvim support vue? what if we clear the filetypes in tsserver?

**Comment by Alexis12119** [comment]
Let me test. But, If I remember correctly no.

**Comment by Alexis12119** [comment]
> But doesn't https://github.com/pmizio/typescript-tools.nvim support vue? what if we clear the filetypes in tsserver?

I disabled it so that it won't conflict on the `typescript-tools.nvim`.

https://github.com/Alexis12119/nvim-config/blob/main/lua/plugins/lsp/configs/mason.lua#L89

**Comment by KevinNitroG** [comment]
Can you try and test if the typescript-tool.opts.settings.separate_diagnostic_server = false?

**Comment by Alexis12119** [comment]
Fixed the issue by doing that

**Comment by KevinNitroG** [comment]
😈

**Comment by Alexis12119** [comment]
I pushed the commit now for the fix.

**Comment by KevinNitroG** [comment]
But wait, are you using vtsls along with typescript-tool? There are 2 lsps? :))
Is it quite odd 😶?

**Comment by Alexis12119** [comment]
Nope. I just set it up

**Comment by KevinNitroG** [comment]
> Nope. I just set it up

Ouh alright ((:

**Comment by Alexis12119** [comment]
I won't run two `LSP` :laughing: because that's insane and I have only 4GB Ram.

**Comment by KevinNitroG** [comment]
> I won't run two `LSP` 😆 because that's insane and I have only 4GB Ram.

That's insane. How can you live with that 4GB? ((: Do you think about buying a new computer or upgrade the RAM?

**Comment by Alexis12119** [comment]
I'm not rich :cry: so I can only buy a new one once I got a job after finishing college.

**Comment by Alexis12119** [comment]
> > I won't run two `LSP` 😆 because that's insane and I have only 4GB Ram.
> 
> That's insane. How can you live with that 4GB? ((: Do you think about buying a new computer or upgrade the RAM?

Just getting used to it. That's why I'm using linux cause it's lightweight

**Comment by KevinNitroG** [comment]
> I'm not rich 😢 so I can only buy a new one once I got a job after finishing college.

Good luck 😉 In my country Vietnam they often say IT (it means Computer Science) is the king of job 🐧

> But over the last few years the IT job market has been quite hard to find a job 😴 because many people are learning IT.

**Comment by KevinNitroG** [comment]
@Alexis12119 https://github.com/pmizio/typescript-tools.nvim/issues/130 maybe we need to consider this 🌝

**Comment by KevinNitroG** [comment]
@Alexis12119 maybe we we have to consider this 🌝

https://github.com/pmizio/typescript-tools.nvim/issues/130#issuecomment-1674438729

**Comment by Alexis12119** [comment]
Yup, so I'll revert the changes?

**Comment by KevinNitroG** [comment]
Many people say that tsserver is slow. I wonder is there a an LSP which is fast like ruff (written in Rust) for Python? 🌞

**Comment by KevinNitroG** [comment]
> Yup, so I'll revert the changes?

I think with your low RAM, disable it maybe better

**Comment by Alexis12119** [comment]
> Many people say that tsserver is slow. I wonder is there a an LSP which is fast like ruff (written in Rust) for Python? 🌞

Some people said `vtsls` is better than `tsserver`. But, I'm not sure if that's true.

**Comment by Alexis12119** [comment]
> > Yup, so I'll revert the changes?
> 
> I think with your low RAM, disable it maybe better

yeah, things are really smooth

**Comment by KevinNitroG** [comment]
> > Many people say that tsserver is slow. I wonder is there a an LSP which is fast like ruff (written in Rust) for Python? 🌞
> 
> Some people said `vtsls` is better than `tsserver`. But, I'm not sure if that's true.

Just use the more stars one ((: That's my way of doing things haha

**Comment by Alexis12119** [comment]
> > > Many people say that tsserver is slow. I wonder is there a an LSP which is fast like ruff (written in Rust) for Python? 🌞
> > 
> > 
> > Some people said `vtsls` is better than `tsserver`. But, I'm not sure if that's true.
> 
> Just use the more stars one ((: That's my way of doing things haha

yeah, most of the time that's the factor to consider

**Comment by Alexis12119** [comment]
I tested both just now and they're both have slow startup :laughing: , but in `typescript-tools.nvim` there's only one process running.
