### ISSUE TITLE
feat(cmp): our formatting opts is conflicting with nvchad cmp styles

### ISSUE THREAD

**Issue by Alexis12119** [Alexis12119/nvim-config#58]
@KevinNitroG, do you think I'll just remove our formatting option to adapt with NvChad cmp styles? 'cause they'll have a feature in `cmp` that we can't use if we're not gonna remove our current formatting `opts`. The downside of it is we can't have database icon for `vim-dadbod-completion`.

**Comment by KevinNitroG** [comment]
I don't mind if the icon of DB is gone (: But what is that, the NvChad cmp feature? 😗😗

**Comment by Alexis12119** [comment]
From siduck:

![image](https://github.com/user-attachments/assets/1fdcde37-3388-4c59-ade6-30e1b096c098)


One of the cmp styles.
![240902_11h53m04s_screenshot](https://github.com/user-attachments/assets/94aa2e49-2f95-4edf-9964-9aa805630fda)

**Comment by Alexis12119** [comment]
This is really cool
![240902_12h16m05s_screenshot](https://github.com/user-attachments/assets/3f3e4d80-0f69-4c0d-b9ee-f1681d192ace)

**Comment by KevinNitroG** [comment]
I'm so laggy I don't know what's going on ((: I'm just back from a vacation 😆

**Comment by Alexis12119** [comment]
> I'm so laggy I don't know what's going on ((: I'm just back from a vacation 😆

I sent 3 photos
