### ISSUE TITLE
request remove `lazy-lock.json` in repo

### ISSUE THREAD

**Issue by KevinNitroG** [Alexis12119/nvim-config#6]
Hi, I just wanna suggest removing `lazy-lock.json` to easily sync *(merge)* your repo as upstream to other users' repos. Or do I misunderstand your purpose? 🫠😶‍🌫️

**Comment by Alexis12119** [comment]
I'll probably just change the path
```lua
lockfile = vim.fn.stdpath "data" .. "/lazy-lock.json",
-- Window: ~/AppData/Local/nvim-data
-- Linux: ~/.local/share/nvim/
```

Is this alright?

**Comment by KevinNitroG** [comment]
> I'll probably just change the path
> 
> ```lua
> lockfile = vim.fn.stdpath "data" .. "/lazy-lock.json",
> -- Window: ~/AppData/Local/nvim-data
> -- Linux: ~/.local/share/nvim/
> ```
> 
> Is this alright?

huhm that sounds great. I haven't seen that config yet 🫡
