### ISSUE TITLE
make OS variable globally

### ISSUE THREAD

**Issue by KevinNitroG** [Alexis12119/nvim-config#60]
There are many places where you (and I) have specific configs for each OS. Why don't we just declare a global variable in init.lua? 😶‍🌫️

**Comment by Alexis12119** [comment]
Or maybe put in a file called globals.lua and require it at the top of init.lua?

**Comment by Alexis12119** [comment]
If you agree, I'll probably push it later 'cause I have to attend now in my college.

**Comment by Alexis12119** [comment]
Well, I pushed it now :laughing: .

**Comment by KevinNitroG** [comment]
Wow so cool ((: Thank you so much! Have a good day my foreign friend 😁

**Comment by KevinNitroG** [comment]
also let's apply to any place that we check OS too ((:

**Comment by KevinNitroG** [comment]
Oh you forgot to add global OS variable 🙀

**Comment by KevinNitroG** [comment]
I've seen some nvim plugin repos use like this

```lua
vim.g.iswin = uv.os_uname().sysname:match('Windows')
vim.g.ismac = uv.os_uname().sysname == 'Darwin'
vim.g.is_ten = vim.version().minor >= 10
```

```lua
vim.g.is_windows = uv.os_uname().version:match 'Windows'
```

**Comment by Alexis12119** [comment]
> I've seen some nvim plugin repos use like this
> 
> ```lua
> vim.g.iswin = uv.os_uname().sysname:match('Windows')
> vim.g.ismac = uv.os_uname().sysname == 'Darwin'
> vim.g.is_ten = vim.version().minor >= 10
> ```
> 
> ```lua
> vim.g.is_windows = uv.os_uname().version:match 'Windows'
> ```

Create a pr for it. thanks

**Comment by Alexis12119** [comment]
I probably misunderstood you sorry for that.

**Comment by KevinNitroG** [comment]
I'm a bit busy too 😅 I will create a PR later when I have done all my homework 😁
