### ISSUE TITLE
nvchad color preview in cmp is out now

### ISSUE THREAD

**Issue by KevinNitroG** [Alexis12119/nvim-config#69]
ye just add `lspkind_text = true` and `format_color = {tailwind = true}` like below hehe

```lua
M.ui = {
  ...
  cmp = {
    lspkind_text = true,
    style = "default", -- default/flat_light/flat_dark/atom/atom_colored
    format_colors = {
      tailwind = true,
    },
  },
  ...
}
```

**Comment by Alexis12119** [comment]
Yup, I know that. I hope that'll be also applicable to the atom style 'cause I like it.

**Comment by KevinNitroG** [comment]
> Yup, I know that. I hope that'll be also applicable to the atom style 'cause I like it.

![image](https://github.com/user-attachments/assets/3d4dbd95-a718-45e0-8545-d597a895a818)

yeah it works with atom your fav stylee

**Comment by Alexis12119** [comment]
I think it looks better with the `default` style so I'll just use the `default`.

**Comment by Alexis12119** [comment]
Oh, before I forgot I just wanna let you know I brought a new laptop which have 16GB RAM now, but sadly it only have 240GB SSD so dual booting is kinda challenge here and it only have integrated graphics card.

**Comment by KevinNitroG** [comment]
> Oh, before I forgot I just wanna let you know I brought a new laptop which have 16GB RAM now, but sadly it only have 240GB SSD so dual booting is kinda challenge here and it only have integrated graphics card.

Yoh, that's coooll (((: how about installing windows 11 LTSC and Arch 🥳

**Comment by Alexis12119** [comment]
I just use a Windows 10 and Endeavour OS for the linux one.

**Comment by KevinNitroG** [comment]
> I just use a Windows 10 and Endeavour OS for the linux one.

Oh Windows 10 thats a good choice for smaller storage capacity. I'm currently using windows 11 home with 240GB and it has taken up my Windows partition 160GB 🌝 I have my data partition separated.
