### ISSUE TITLE
Request: Custom `statusline` module (`total_lines`)

### ISSUE THREAD

**Issue by KevinNitroG** [Alexis12119/nvim-config#7]
Hi again 😁. The statusline renders wrong when I set `statusline.separator_style = default`. It isn't round. Here is the image of the situation.

![image](https://github.com/Alexis12119/nvim-config/assets/86353526/c9107a11-c40e-4975-a4d6-db8a815d8852)

I have tried to set `default_sep_icons.default` = `default_sep_icons.round` in `statusline.modules.total_lines` but it still doesn't work. =))

Thank you. Your config is very nice. I would stay here for long time, because it has a nice look from NvChad but very clean keymaps setup.

**Comment by Alexis12119** [comment]
Hello, there's something I need to do so I applied a temporary fix for now.

![240420_07h03m26s_screenshot](https://github.com/Alexis12119/nvim-config/assets/74944536/10863ea2-eacd-4f7d-a1a1-3f9f9c1a89e8)
