### ISSUE TITLE
bug(nvim-notify): bottom right noti overlaps tabufline

### ISSUE THREAD

**Issue by KevinNitroG** [Alexis12119/nvim-config#72]
https://github.com/rcarriga/nvim-notify/issues/295

I just want to notice you about this :))

**Comment by Alexis12119** [comment]
yeah, I noticed it before

**Comment by KevinNitroG** [comment]
> yeah, I noticed it too before and I'm just trying to bear with it.

I feel a bit inconvenient sometimes ((:

**Comment by Alexis12119** [comment]
> > yeah, I noticed it too before and I'm just trying to bear with it.
> 
> I feel a bit inconvenient sometimes ((:

For me, it's not sometimes, but always :laughing:

**Comment by Alexis12119** [comment]
> > yeah, I noticed it too before and I'm just trying to bear with it.
> 
> I feel a bit inconvenient sometimes ((:

Then, I'll use the fix from that issue for now.

**Comment by Alexis12119** [comment]
@KevinNitroG, Have you tried `snacks.nvim`. It has a great notifier, but contains many functionalities that we already have.

**Comment by KevinNitroG** [comment]
> @KevinNitroG, Have you tried `snacks.nvim`. It has a great notifier, but contains many functionalities that we already have.
I havent tried it yet. I have taken a look around snacks.nvim and it's kinda cool. But as you said, we already have some of those configs. I we dont need to use snacks, because using it make the dependencies larger.

https://github.com/rcarriga/nvim-notify is good though 💃🏻

**Comment by Alexis12119** [comment]
> > @KevinNitroG, Have you tried `snacks.nvim`. It has a great notifier, but contains many functionalities that we already have.
> > I havent tried it yet. I have taken a look around snacks.nvim and it's kinda cool. But as you said, we already have some of those configs. I we dont need to use snacks, because using it make the dependencies larger.
> 
> https://github.com/rcarriga/nvim-notify is good though 💃🏻

I hope `nvim-notify` will do what the notifier of `snacks.nvim` does since it limits the notification up to 3 and not make things overpopulated.

**Comment by KevinNitroG** [comment]
Nvim notify may be ... Dead now 🌚

**Comment by Alexis12119** [comment]
> Nvim notify may be ... Dead now 🌚

Oh, their commits was 3 months ago.
