### ISSUE TITLE
ques(Lazy): is it neccessary to install rock

### ISSUE THREAD

**Issue by KevinNitroG** [Alexis12119/nvim-config#73]
https://github.com/Alexis12119/nvim-config/blob/f10ec7e62f4a5d37bd749bd4ca578a29e53ca6b5/lua/plugins/utils.lua#L15C1-L21C2

Because as [Lazy' doc](https://lazy.folke.io/configuration), it supports Rock itself by default. Also, Luasnip requires jsregexp ([this repo](https://github.com/kmarius/jsregexp) I guess). So that...

I guess! We can config luasnip like this?

```lua
{
  "L3MON4D3/LuaSnip",
  dependencies = {
    "rafamadriz/friendly-snippets",
    "kmarius/jsregexp",
     },
}
```

I need confirmation from LuaSnip https://github.com/L3MON4D3/LuaSnip/pull/1252

**Comment by KevinNitroG** [comment]
https://github.com/Alexis12119/nvim-config/blob/f10ec7e62f4a5d37bd749bd4ca578a29e53ca6b5/lua/plugins/neorg.lua#L5

Also this https://lazy.folke.io/news#11x

With changes of Lazy :P

**Comment by Alexis12119** [comment]
> https://github.com/Alexis12119/nvim-config/blob/f10ec7e62f4a5d37bd749bd4ca578a29e53ca6b5/lua/plugins/neorg.lua#L5
> 
> Also this https://lazy.folke.io/news#11x
> 
> With changes of Lazy :P

Thanks for the good news.
