### ISSUE TITLE
i got this error while opening java files

### ISSUE THREAD

**Issue by jayadeep11** [Alexis12119/nvim-config#74]
![image](https://github.com/user-attachments/assets/e7cf5917-8473-4911-a87e-06893adfd5b3)

**Comment by KevinNitroG** [comment]
Waiting for @Alexis12119 reply 🌝

**Comment by Alexis12119** [comment]
> Waiting for @Alexis12119 reply 🌝

Wait, I'm not in my house right now

**Comment by Alexis12119** [comment]
> ![image](https://private-user-images.githubusercontent.com/163034023/393161672-e7cf5917-8473-4911-a87e-06893adfd5b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0ODAyNDEsIm5iZiI6MTczMzQ3OTk0MSwicGF0aCI6Ii8xNjMwMzQwMjMvMzkzMTYxNjcyLWU3Y2Y1OTE3LTg0NzMtNDkxMS1hODdlLTA2ODkzYWRmZDViMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQxMDEyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzYwMDhjNGE2MDFhMzEyOTU5NDlkMGI5MGM1YzFhMDQzMzVhNTk2MjM5OTk1MTU5NTk3ZGIxZWI1NTJiNzQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.AbnLuaPtMLgmIjRruFdcXENbG5xAjiwUgCrbadUzstA)

I just had a fix about `lombok` which now uses the new path of the `lombok.jar`.

![241206_18h19m30s_screenshot](https://github.com/user-attachments/assets/b81e9e89-462b-4090-9540-3e5ad2e7ef4c)

**Comment by Alexis12119** [comment]
@KevinNitroG , Do you think I should add a global variable for utilizing lombok? Maybe he need to install the `lombok-nightly` after pulling my latest changes.

**Comment by jayadeep11** [comment]
okay !

**Comment by jayadeep11** [comment]
how to install lombok-nightly

**Comment by Alexis12119** [comment]
> how to install lombok-nightly

Oh, wait did you already install `jdtls`?

If no, then run this:
```lua
:MasonInstall jdtls lombok-nightly
```

**Comment by jayadeep11** [comment]
thank you :)
it works

**Comment by Alexis12119** [comment]
> thank you :) it works

That's nice to know :100:

**Comment by KevinNitroG** [comment]
> @KevinNitroG , Do you think I should add a global variable for utilizing lombok? Maybe he need to install the `lombok-nightly` after pulling my latest changes.

Ouh ouhm... I don't know anything about java :))

**Comment by KevinNitroG** [comment]
> > > @KevinNitroG , Do you think I should add a global variable for utilizing lombok? Maybe he need to install the `lombok-nightly` after pulling my latest changes.
> > 
> > 
> > Ouh ouhm... I don't know anything about java :))
> 
> Well, I think it's best to keep it since it's useful when it comes to java programming

I do not intend to learn java and any subject that relates to java. Also with C# (but I'm doing C# project in this semester :(( )
