### ISSUE TITLE
lsp keymaps not enabled for typescript-language-tools

### ISSUE THREAD

**Issue by serpro69** [Alexis12119/nvim-config#75]
Hi 👋 ,
I've noticed that https://github.com/Alexis12119/nvim-config/blob/549be8936a0cb7b4da7ce2dd46d2e9158269c373/lua/plugins/lsp/opts.lua#L7 are not applied to typescript-tools plugin. Probably because it's outside of cmp_nvim_lsp "ecosystem"?

So far I just copy-pasted the mappings and applied them in the plugin, which seems to work fine:

```diff
diff --git a/lua/plugins/lsp/configs/typescript-tools.lua b/lua/plugins/lsp/configs/typescript-tools.lua
index 7423c6c..87d8206 100644
--- a/lua/plugins/lsp/configs/typescript-tools.lua
+++ b/lua/plugins/lsp/configs/typescript-tools.lua
@@ -1,12 +1,36 @@
 ---@type NvPluginSpec
 -- NOTE: For Typescript
+
+local keymap = vim.keymap.set
+
+local function lsp_keymaps(bufnr)
+  -- keymap("n", "gD", vim.lsp.buf.declaration, { buffer = bufnr, silent = true })
+  keymap("n", "gD", "<cmd>Lspsaga finder<cr>", { buffer = bufnr, silent = true })
+  keymap("n", "gd", "<cmd>Lspsaga goto_definition<cr>", { buffer = bufnr, silent = true })
+  keymap("n", "<leader>la", vim.lsp.buf.code_action, { buffer = bufnr, desc = "LSP | Code Action", silent = true })
+  -- keymap("n", "gd", vim.lsp.buf.definition, {buffer = bufnr, silent = true})
+  keymap("n", "gl", "<cmd>Lspsaga show_line_diagnostics<cr>", { buffer = bufnr, silent = true })
+  keymap("n", "gp", "<cmd>Lspsaga peek_definition<cr>", { buffer = bufnr, silent = true })
+  -- keymap("n", "K", vim.lsp.buf.hover, {buffer = bufnr, silent = true})
+  keymap("n", "K", "<cmd>Lspsaga hover_doc<cr>", { buffer = bufnr, silent = true })
+  keymap("n", "gI", "<cmd>Telescope lsp_implementations<cr>", { buffer = bufnr, silent = true })
+  keymap("v", "<leader>la", vim.lsp.buf.code_action, { buffer = bufnr, desc = "LSP | Code Action", silent = true })
+end
+
 return {
   "pmizio/typescript-tools.nvim",
   event = "BufReadPost",
+  dependencies = {
+    "nvim-lua/plenary.nvim",
+    "neovim/nvim-lspconfig",
+  },
   opts = {
-    on_attach = function(client)
+    on_attach = function(client, bufnr)
       client.server_capabilities.documentFormattingProvider = false
       client.server_capabilities.documentRangeFormattingProvider = false
+      lsp_keymaps(bufnr)
     end,
     settings = {
       separate_diagnostic_server = false, -- Disable separate diagnostic server
@@ -15,6 +39,9 @@ return {
         includeCompletionsForModuleExports = true,
         quotePreference = "auto",
       },
     },
   },
 }

```

Don't know if there's any better way to fix this.

---

upd, I guess this might be a better option?

```diff
diff --git a/lua/plugins/lsp/configs/typescript-tools.lua b/lua/plugins/lsp/configs/typescript-tools.lua
index 7423c6c..4bf8c97 100644
--- a/lua/plugins/lsp/configs/typescript-tools.lua
+++ b/lua/plugins/lsp/configs/typescript-tools.lua
@@ -1,12 +1,21 @@
 ---@type NvPluginSpec
 -- NOTE: For Typescript
+
+local keymaps = require("plugins.lsp.opts").lsp_keymaps
+
 return {
   "pmizio/typescript-tools.nvim",
   event = "BufReadPost",
+  dependencies = {
+    "nvim-lua/plenary.nvim",
+    "neovim/nvim-lspconfig",
+  },
   opts = {
-    on_attach = function(client)
+    on_attach = function(client, bufnr)
       client.server_capabilities.documentFormattingProvider = false
       client.server_capabilities.documentRangeFormattingProvider = false
+      keymaps(bufnr)
     end,
     settings = {
       separate_diagnostic_server = false, -- Disable separate diagnostic server
@@ -15,6 +24,7 @@ return {
         includeCompletionsForModuleExports = true,
         quotePreference = "auto",
       },
     },
   },
 }


diff --git a/lua/plugins/lsp/opts.lua b/lua/plugins/lsp/opts.lua
index a5837b4..d69f7f7 100644
--- a/lua/plugins/lsp/opts.lua
+++ b/lua/plugins/lsp/opts.lua
@@ -18,13 +18,16 @@ local function lsp_keymaps(bufnr)
   keymap("v", "<leader>la", vim.lsp.buf.code_action, { buffer = bufnr, desc = "LSP | Code Action", silent = true })
 end
 
+M.lsp_keymaps = lsp_keymaps
+
 -- Highlight symbol under cursor
 local function lsp_highlight(client, bufnr)
   if client.supports_method "textDocument/documentHighlight" then
```

**Comment by KevinNitroG** [comment]
```lua
    on_attach = function(client, bufnr)
      client.server_capabilities.documentFormattingProvider = false
      client.server_capabilities.documentRangeFormattingProvider = false
      -- Add this below
 	  require("plugins.lsp.opts").on_attach(client, bufnr)
    end,
```

I guess. I think... but waiting for @Alexis12119 for better config

**Comment by KevinNitroG** [comment]
But no @Alexis12119, I think we can remove that on_attach prop. Because in the past, I created an issue said that lsp conflicts with conform. I might be wrong.

In conform docs, it can handle it, it has LSP fallback.

**Comment by Alexis12119** [comment]
> ```lua
>     on_attach = function(client, bufnr)
>       client.server_capabilities.documentFormattingProvider = false
>       client.server_capabilities.documentRangeFormattingProvider = false
>       -- Add this below
>  	  require("plugins.lsp.opts").on_attach(client, bufnr)
>     end,
> ```
> 
> I guess. I think... but waiting for @Alexis12119 for better config

That's what I think too.

**Comment by Alexis12119** [comment]
I pushed it now.

**Comment by Alexis12119** [comment]
The funny thing is that we don't need to set it in order to work maybe that's the reason why I didn't noticed this issue.

**Comment by Alexis12119** [comment]
![Screenshot From 2024-12-14 22-11-46](https://github.com/user-attachments/assets/6dc858cc-9cae-4112-82f0-ccb6247f2290)
I didn't put any `on_attach` function here, but still works fine.

**Comment by KevinNitroG** [comment]
> ![Screenshot From 2024-12-14 22-11-46](https://private-user-images.githubusercontent.com/74944536/395787427-6dc858cc-9cae-4112-82f0-ccb6247f2290.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxODk0ODIsIm5iZiI6MTczNDE4OTE4MiwicGF0aCI6Ii83NDk0NDUzNi8zOTU3ODc0MjctNmRjODU4Y2MtOWNhZS00MTEyLTgyZjAtY2NiNjI0N2YyMjkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDE1MTMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmNDMwMTgxNWJmNzA4MTc4YjFkYjJkZDE5NWNiNGNlMmM3MWJlZDBjMzJjNDk5OGYyMjBmMTU0MmIxNzIxZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9WJlN-NHR1_D0Su9shsoQq_GLp664CWCLc-OfuzDf-Y) I didn't put any `on_attach` function here, but still works fine.

Just remove the on_attach prop, it will be fine :}]
