### ISSUE TITLE
issue: event "BufReadPost"

### ISSUE THREAD

**Issue by KevinNitroG** [Alexis12119/nvim-config#77]
Many plugins' events are `BufReadPost,` which don't start when entering nvim to edit a file directly from the commandline. For example, in' vim README.md`, the `BufReadPost` hasn't triggered. I think `User FilePost` and `VeryLazy` are more suitable.

**Comment by Alexis12119** [comment]
oh, ok

**Comment by Alexis12119** [comment]
I pushed it now.
