### ISSUE TITLE
Feat Request: Show mark in code line sidebar

### ISSUE THREAD

**Issue by KevinNitroG** [Alexis12119/nvim-config#8]
Hi. Could you implement to make the mark shown in code line sidebar in your free time? Here is an example from LazyVim <3

![image](https://github.com/Alexis12119/nvim-config/assets/86353526/17f55c65-81f8-46c1-929c-1676216b4ac1)

If it seems to break your config style, then could you make it togglable to show? 😅

Thank you.

**Comment by Alexis12119** [comment]
Like this?

![240420_19h33m08s_screenshot](https://github.com/Alexis12119/nvim-config/assets/74944536/69792d9e-2534-41bd-a56c-057f0f946ac3)

**Comment by Alexis12119** [comment]
You can see here their own implementation.

https://github.com/LazyVim/LazyVim/blob/bb36f71b77d8e15788a5b62c82a1c9ec7b209e49/lua/lazyvim/util/ui.lua#L55-L63


I just used this plugin.

https://github.com/chentoast/marks.nvim

**Comment by KevinNitroG** [comment]
> You can see here their own implementation.
> 
> https://github.com/LazyVim/LazyVim/blob/bb36f71b77d8e15788a5b62c82a1c9ec7b209e49/lua/lazyvim/util/ui.lua#L55-L63
> 
> I just used this plugin.
> 
> https://github.com/chentoast/marks.nvim

thank you for your very quick respond and implementation 🥰
